# general settings
name: train_CRAFT_RGB_IR_0904
model_type: CRAFT_Model
scale: 1
num_gpu: auto
manual_seed: 33

# dataset and data loader settings
datasets:
  train:
    name: RGB_IR # DIV2K
    type: PairedImageOutputBWDataset # PairedImageDataset
    dataroot_gt: datasets/RGB_IR_0730_drop_train_B # datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: datasets/RGB_IR_0730_drop_train_A # datasets/DIV2K/DIV2K_train_LR_bicubic/X2
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 352
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: RGB_IR # Set5
    type: PairedImageOutputBWDataset
    dataroot_gt: datasets/RGB_IR_0730_drop_test_B
    dataroot_lq: datasets/RGB_IR_0730_drop_test_A
    io_backend:
      type: disk

# network structures
network_g:
  type: CRAFT
  upscale: 1
  in_chans: 3
  out_chans: 1
  img_size: 352
  window_size: 16
  img_range: 1.
  depths: [2, 2, 2, 2]
  embed_dim: 48
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: SmoothL1Loss #L1Loss
    loss_weight: 1.0
    reduction: mean

  edge_opt:
    type: EdgeSmoothL1Loss 
    loss_weight: 1.0
    reduction: mean
  
  perceptual_opt:
    type: PerceptualLoss 
    layer_weights: {'conv5_4': 1.}
    perceptual_weight: 1.0
    style_weight: 1.0  
    criterion: smoothl1

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true # false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

